name: Deploy the react project 
on:
 push:
  branches :
   -main 
jobs: 
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASWORDS }}
      - run: docker build kamal2274/react-test -f Dockerfile.dev
      - run: docker run -e CI=true kamal2274/react-test npm run test      
